# Generated by Django 5.2.8 on 2025-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
