# Generated by Django 5.2.8 on 2025-12-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_issue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1),
        ),
    ]
